### ISSUE TITLE
All of Railcraft is broken, and short of restoring everything in IC2, TechReborn, and Immersive Engineering, there is no way this pack will EVER be stable

### ISSUE THREAD

**Issue by Solverbolt** [FTBTeam/FTB-Ultimate-Reloaded#149] opened 2019-03-17 11:53 UTC
* **Modpack Version**: 
1.3
* **Issue**: 
All railcraft machines that need power, wont accept any power, even using the energy converter bridge system, and any attempt to use alternatives, in this case, Immersive engineering, will corrupt a player file
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
try it yourself, though likelihood is that if you attempt to do it in Creative mode, it wont duplicate the issue
* **Mod/s Affected**: 
The entire pack. 
* **Known Fix**: 
Rebuild the pack and remove Railcraft and Buildcraft. Neither has any ETA for a stable update, and CovertJaguar and his team are more than happy to blame anyone else for their failures on updating. They have made that very clear in the multitude of open tickets in their own support Github.  

While I understand that nostalgia is nice, it does not work if certain mod developers are unwilling to accept that they screwed up with recent updates. Instead of focusing on nostalgia, why not instead build a proper expert mode progression pack that uses current Minecraft version or at least 1.12.2, and make a balanced modpack, that offers a real challenge.

**Comment by CovertJaguar** [comment] 2019-03-17 17:55
Your trolling is not appreciated or appropriate. You have a history of attacking mods you don't like.

The stable release you claim will never be ready was released two days ago.

Railcraft machines use Railcraft Charge as a power source. We provide means to convert EU and FE to Charge. Your claims are misleading and not in good will.

**Comment by Solverbolt** [comment] 2019-03-17 19:42
Actually they are not Covert, and I have a dozen other players to back that claim. We have been trying to work with you and your team, and you have constantly tried to shift the blame for the issues happening within your mod to other mods, making the claim that it is causing the issue, not your mod, despite the mountains of data we have provided to you. 

this was never about trolling, this is about correcting an issue, even if it means removing your mods from the pack till you can confirm that you have ACTUALLY fixed the issues we continually report.

**Comment by CovertJaguar** [comment] 2019-03-17 19:48
You haven't tried to work with us at all. You are the only one who has ever made this claim. Whenever we ask you for data you ignore us. Our suggestions and solutions fall on deaf ears.

**Comment by Solverbolt** [comment] 2019-03-17 19:50
Right... I can prove that wrong, since Cube and I have been working on this together, and Both him and the other server owner, plus myself have all agreed that Railcraft has become a joke. want to get a screenshot of that?

**Comment by CovertJaguar** [comment] 2019-03-17 20:01
Prove what wrong? I've never talked to Cube or anyone else you are talking about. What does a screenshot of your buddies calling Railcraft a joke prove?

I have some screenshots too. 

These _all_ work:
![2019-03-17_12 59 26](https://user-images.githubusercontent.com/1521970/54497156-a325fe00-48b4-11e9-9f20-2242958e1b62.png)
![2019-03-17_12 57 40](https://user-images.githubusercontent.com/1521970/54497157-a325fe00-48b4-11e9-8edf-79f7672c62e0.png)
![2019-03-17_12 57 51](https://user-images.githubusercontent.com/1521970/54497159-a3be9480-48b4-11e9-9c77-4b5e57602bf6.png)

**Comment by Solverbolt** [comment] 2019-03-17 20:21
And none of those Pipes, are in your current mod.  Same with the engines. The boiler recipe shows as there, but not there, no recipe. Oh, and AS I SENT A SCREENSHOT OF THE CRUSHER THREE DAYS AGO, NOT ACCEPTING POWER, 
![2019-03-17_13 19 58](https://user-images.githubusercontent.com/38087746/54497414-ae2e5d80-48b7-11e9-8979-4684b5a018ce.png)
![2019-03-17_13 20 00](https://user-images.githubusercontent.com/38087746/54497415-ae2e5d80-48b7-11e9-9aca-f265dfaa356c.png)
![2019-03-17_13 20 02](https://user-images.githubusercontent.com/38087746/54497416-ae2e5d80-48b7-11e9-9dad-bf1198782a1f.png)
![2019-03-17_13 20 04](https://user-images.githubusercontent.com/38087746/54497417-ae2e5d80-48b7-11e9-8923-c6d20dca820a.png)
![2019-03-17_13 20 05](https://user-images.githubusercontent.com/38087746/54497418-ae2e5d80-48b7-11e9-96de-b5f7735e0047.png)
![2019-03-17_13 20 07](https://user-images.githubusercontent.com/38087746/54497419-aec6f400-48b7-11e9-9944-30683a8ab653.png)
![2019-03-17_13 20 09](https://user-images.githubusercontent.com/38087746/54497420-aec6f400-48b7-11e9-9804-e25e9f8fa438.png)

**Comment by Solverbolt** [comment] 2019-03-17 20:23
Your Rock Crusher is actually corrupting peoples inventories. When anyone attempts to right click to open the GUI, it is making their inventory disappear and has to be restored from a backup.

**Comment by CovertJaguar** [comment] 2019-03-17 20:41
Recipes are right here:
![boiler](https://user-images.githubusercontent.com/1521970/54497601-be473c80-48b9-11e9-97f7-38e5292503b1.png)

I have no idea what you are trying to show me.

No one has reported the inventory thing, nor can I replicate it. I won't rule out that it could be a bad mod interaction, but as I said, first I've heard of it.

You sent me a screen shot of the Crusher not connecting to Thermal conduits. Its not supposed to. The conduits _would_ connect to the Flux Transformer pictured earlier though.

**Comment by Solverbolt** [comment] 2019-03-17 20:45
I was showing you that the PIPES you are using, Do not exist. The recipes for the fuel boxes are also missing. The images are there yes, but like many other recipes, the recipes are missing.  And do not think this entire issue is all about your mod, its just the main problem, as we have tried talking to you repeatedly about the ghost carts.  

Flux Transformer would be nice, except it connects to nothing but buildcraft, everything else wont touch it, and there is no engines in buildcraft either, so no way to generate power to begin with, in either mod

**Comment by CovertJaguar** [comment] 2019-03-17 20:51
You are just plain wrong. The Flux Transformer does not use the Buildcraft MJ API. It uses the Forge Energy API. Most mods will connect to the Forge Energy API. The picture I posted of it working is using a Biomass Engine from Forestry.

Wire is right here:
![wire](https://user-images.githubusercontent.com/1521970/54497718-51cd3d00-48bb-11e9-868f-5ef3d8d82d76.png)

Here is the recipe:
![2019-03-17_13 48 33](https://user-images.githubusercontent.com/1521970/54497733-6c071b00-48bb-11e9-97e2-13e0006a161b.png)

If by ghost carts, you mean the ones that are created by world gen? Yeah, you mentioned that. We found nothing but what was expected. In response you got mad.

**Comment by Solverbolt** [comment] 2019-03-17 20:58
actually i left it to TheLittleCube, as we felt it would better if he handled that. But go ahead, make false claims.  So go ahead and pretend you are on the upper hand, Since you are likely just using base modded minecraft with ONLY your mod loaded, you have no concept of where the problem is. at this point, Yes, I am going to ignore you, You are abusive, ignorant, and you lack the basic problem solving thought to be recognized as anything but a child

**Comment by CovertJaguar** [comment] 2019-03-17 20:58
![2019-03-17_13 58 03](https://user-images.githubusercontent.com/1521970/54497827-ba68e980-48bc-11e9-9fa2-4ccf0c06c8a8.png)
![2019-03-17_13 57 58](https://user-images.githubusercontent.com/1521970/54497828-bb018000-48bc-11e9-9464-60a3af92c00f.png)

**Comment by CovertJaguar** [comment] 2019-03-17 21:02
I don't even know what mods you are using, no one else is reporting these issues. You have consistently tossed random issues at us and told us to "solve" them without giving us any context or assistance. When we tell you are using the mod wrong you get upset.

**Comment by Solverbolt** [comment] 2019-03-17 21:12
2:46 AM] TheLittleCube: I have only spoken to him on railcraft
[2:46 AM] TheLittleCube: as its the only thing that is fucking the server
[2:46 AM] TheLittleCube: which is why we haven't updated

[3:45 AM] TheLittleCube: and I have said fuck railcraft
[3:45 AM] TheLittleCube: to many issues

**Comment by CovertJaguar** [comment] 2019-03-17 21:19
Ah... him. Liach looked at the files he sent and found exactly what we expected to find. IE. Working as intended. No evidence of any bug.

**Comment by LemADEC** [comment] 2019-03-17 21:23
The inventory 'corruption' is just a visual glitch due to client/server desync. Solved by just reconnecting.
Because of the glitch, players are moving invalid items, dropping/loosing them. I've only used Railcraft with FTB Ultimate Reloaded, so no idea what interaction is causing this.

**Comment by Solverbolt** [comment] 2019-03-17 21:55
> The inventory 'corruption' is just a visual glitch due to client/server desync. Solved by just reconnecting.
> Because of the glitch, players are moving invalid items, dropping/loosing them. I've only used Railcraft with FTB Ultimate Reloaded, so no idea what interaction is causing this.

the first part, it only happens when interacting with certain railcraft machines, Rock Crusher and powered Rolling Machine, but even relogging did not fix the issue. 

Second part, I remember railcraft in the very early days, i enjoyed it back them, because I was one of those people who thought the multiblock tanks were amazing, and i would fill them with all the various liquids from all the mods, at one point, i had a base that had over 250 max size tanks filled with various liquids.  As such, in the last year, a lot of us have noticed regular issues popping up with railcraft, and frankly, we feel that the mod has not lived up to times past, nothing really new has been put in place other than a new gui skin for the machines, among other visual things.

**Comment by CovertJaguar** [comment] 2019-03-17 22:25
In that time, tracks have been rewritten to make handling them less tedious, rendering had to be scrapped and started over because Mojang, the whole charge framework got rewritten (twice) to solve the electric track lag issues, all the machines had to be rewritten because of Mojang, the multiblock code was rewritten because it was a pain to maintain, the inventory, fluid, and power code had to be rewritten because Forge, the train code was rewritten to make trains more reliable, GUIs were rewritten to make them more standardized and to reduce the insane amount of code duplication.

If nothing new has been added, that's why. That's why Railcraft has been in Beta hell forever. That's why there are bugs. I've burned myself out fixing all this stuff because its boring and tedious work. I like adding new stuff too, can't do that when Mojang or Forge breaks everything every six months.

Users who can't be civil and respectful do _not_ help the situation. When you came to us about the train issue, I immediately made it a high priority, even delayed a release because of it. If it was really doing as you said, it _had_ to be fixed ASAP. I set liach to try and duplicate it. I inspected profiling logs for a couple hours, found some unrelated things, nothing related to your complaints though. We added new code to parse and inspect the files you sent us. We generated new worlds and ran tests to see how many carts are generated by world gen. We spent _days_ on your problem and found _nothing_. In thanks, you and the community attacked me. Could it be a weird mod interaction? I can't rule it out, but those kinds of bugs are shitty to isolate. They take time and reports from several sources in order to identify the common factor. We found nothing, many people came out and said they had no such issues. No one else reported anything remotely similar. We did all that we could humanly do to accommodate you at the expense of both our release schedule and shuffling a couple other projects onto the back burner, which we still haven't gotten back to.

I'm not going to call you names. Though lord knows I feel like it. You've certainly called me enough.

Anyway, I have some cabbage to cook.

**Comment by tfox83** [comment] 2019-03-18 17:34
The release version of Railcraft is included in todays update thanks to CovertJaguar.  The version will be 1.5.0 and will be listed as a beta for a few days.  I am closing and locking this thread.  If you do not want BC or RC in a pack then I suggest not playing packs that contain them.  Maybe make a pack of your own to play so you can be in control of the changes made to said pack.  Any further false claims will result in a ban from our issue trackers.

**Closed as completed by tfox83** 2019-03-18 17:34 UTC
