### ISSUE TITLE
Issue with Forestry multi block farms 

### ISSUE THREAD

**Issue by Thekevaroo** [FTBTeam/FTB-Ultimate-Reloaded#251] opened 2019-06-13 01:53 UTC
* **Modpack Version**: 1.7.1

* **Issue**: Upon upgrade of our server to 1.7.1 - all of our Forestry multi block farms have stopped placing saplings on the humas placed by the multi block. Upon removing and replacing the farm - it successfully rebuilds the multi block and places the humas down and you can hear the farm trying to place the saplings but nothing places. If placed manually the farm collects the wood.

* **Link to Log or Crash File Paste**: Does not cause a crash

* **Is it Repeatable?**: Yes i have repeated this on all forms of the multiblock

* **Mod/s Affected**: Forestry 5.8.2.387

* **Known Fix**: None from me!

**Comment by TheElementalOfDestruction** [comment] 2019-06-15 11:54
Weird. I personally have not been able to reproduce this. What kind of saplings does this occur with?

**Comment by zedoax** [comment] 2019-06-15 16:10
I too have not encountered this.  I have a running rubber+spruce multiblock farm and have not experienced this issue.  
In addition to the saplings used, what size of farm did you use?

**Comment by Thekevaroo** [comment] 2019-06-15 21:43
i am using the max size farm (5x5x4) with oak and rubber saplings. I can hear the farm "placing" as it's trying to but it is not putting the saplings down. I have removed all of the farm blocks and rebuilt - issue still occurs.

**Comment by TheElementalOfDestruction** [comment] 2019-06-15 21:44
Does this occur for you on the smaller farms (ie. 3x3x4)?

**Comment by Thekevaroo** [comment] 2019-06-15 22:05
so far - yep. i will try reinstalling the server version tonight to see if we have a further issue.

**Comment by TheElementalOfDestruction** [comment] 2019-06-15 22:06
Ohhhh, this is happening with the SERVER version.

**Comment by Thekevaroo** [comment] 2019-06-15 22:07
yes indeed it is. We updated our server to 1.7.1 from 1.50 after moving hosts - everything went well - just no farms are working now.

**Comment by TheElementalOfDestruction** [comment] 2019-06-15 22:08
In that case, would you mind posting the forestry config files for the server (if you have access to them) so we can look to see if the issue might reside there?

**Comment by Thekevaroo** [comment] 2019-06-16 01:07
Sorry for the delay - the config is completely default as per the download. We didn't alter it at all.

**Comment by TheElementalOfDestruction** [comment] 2019-06-16 01:29
Default to the 1.50 download or the 1.7.1 download? If the config didn't end up getting updated for some reason then it might be causing your problems.

**Comment by Thekevaroo** [comment] 2019-06-16 04:01
1.7.1
We moved the world from one server to another.

**Comment by TheElementalOfDestruction** [comment] 2019-06-24 16:11
Has reinstalling fixed the problem?

**Comment by tfox83** [comment] 2019-07-23 15:12
Closing as I am not able to reproduce issues.

**Closed as completed by tfox83** 2019-07-23 15:12 UTC
