### ISSUE TITLE
Oil power glitch

### ISSUE THREAD

**Issue by TheGameGeek** [FTBTeam/FTB-Ultimate-Reloaded#76] opened 2019-02-19 07:24 UTC
* **Modpack Version**: 1.0.1

* **Issue**: If you put heavy oil (cool) into the Thermal Generator then it produces power but doesnt use the oil

* **Is it Repeatable?**: Put one bucket of heavy oil into the thermal generator and watch none get used

* **Mod/s Affected**: Tech Reborn

* **Screenshot info**: we were testing this and i originally had 7875mb in the tank i attatched to the thermal generator and this is after it running for about 10 minutes
![2019-02-19_01 53 22](https://user-images.githubusercontent.com/16767836/52996982-29057500-33ed-11e9-971e-903c8de81aef.png)

**Comment by tfox83** [comment] 2019-02-20 16:31
Ill have @modmuss50 take a look at this when he has time.  Thanks

**Comment by modmuss50** [comment] 2019-02-20 17:26
This may have been fixed in 1.1.0 (BC fuel values were off), I cannot reproduce in the latest version of TR

**Comment by tfox83** [comment] 2019-02-20 18:09
perfect, I cannot either, thanks

**Closed as completed by tfox83** 2019-02-20 18:09 UTC
Labels: fixed in dev
