### ISSUE TITLE
Thaumcraft Thaumonomicon won't complete any Thaumic Tinkerer research

### ISSUE THREAD

**Issue by BartMitTyp** [FTBTeam/FTB-Ultimate-Reloaded#379] opened 2020-08-06 07:20 UTC
* **Modpack Version**: 1.9.0

* **Issue**: When trying to complete anything from the Thaumic Tinkerer Research Tree, even though I have all the requirements fullfilled, the "completing ..." text never finishes. The "complete" button is clickable, but there is no progress.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes. To test this, one must only complete the first steps, which takes just a few minutes. (I did that on another world to confirm)

* **Mod/s Affected**: Thaumic Tinkerer 1.12.2-5.0-353c71c and Thaumcraft 6.1.BETA26

**Comment by will-blk** [comment] 2020-11-08 14:45
Same here on modpack version 1.10

**Comment by zellfrey** [comment] 2020-11-25 22:01
This is fixed in the later versions of Thaumic Tinkerer.

The last update for thaumic tinkerer was in May 2020.

They released a new version of the pack in October. This maybe an oversight

**Comment by mxswat** [comment] 2020-11-30 10:47
I can confirm, broken on modpack 1.10

**Comment by 016Nojr** [comment] 2021-05-03 15:53
Thaumic Tinkerer updated

**Closed as completed by 016Nojr** 2021-05-03 15:53 UTC

**Comment by zellfrey** [comment] 2021-05-05 15:45
> Thaumic Tinkerer updated

So what, does this mean that the pack will be updated? Because I stated that the mod updated. But the pack doesn't have the updated version of the mod

**Comment by Sunekaer** [comment] 2021-05-05 20:04
We are working on updating the pack

**Comment by zellfrey** [comment] 2021-05-05 21:50
> We are working on updating the pack

That sounds really good, did SlowPoke ever talk to you about the fan pack update I wanted to push?
