### ISSUE TITLE
Project Red Teleposer

### ISSUE THREAD

**Issue by RougeCiel** [FTBTeam/FTB-Ultimate-Reloaded#295] opened 2019-08-09 16:02 UTC
* **Modpack Version**: 1.7.1 

* **Issue**: When you drop an enderpearl on a charged Teleposer, the game crash and corrupt your world. 

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: Project Red 4.9.1.92

**Comment by WebDragon** [comment] 2019-08-13 22:16
[crash-2019-08-13_17.58.05-server.txt](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/3499074/crash-2019-08-13_17.58.05-server.txt)

Confirmed. just had this happen to me. Restarted and tested for world corruption, but fortunately there was none, (and not about to attempt a retry... the crash was instant).

**Comment by cr998** [comment] 2019-08-14 12:25
had you tried with 1.8.0 ModPack version?
it could be fixed

**Comment by tostamista23** [comment] 2019-08-14 12:37
still happen in 1.8.0

**Comment by WebDragon** [comment] 2019-08-14 15:21
that's the version of the modpack I've been using

**Comment by cr998** [comment] 2019-08-16 13:15
i will check this mod isolated to verify if is a bug of project red or incompatibility between mods

**Comment by Zalgo2462** [comment] 2019-12-08 07:36
Confirmed on version 1.6.0. It only crashed the client not the server.

**Comment by Ernedar** [comment] 2020-04-02 19:50
Hello. Just crashed my server too. 
Project Red version: ProjectRed-1.12.2-4.9.4.120-Base.jar

Crashreport:

```
[20:34:48] [Server thread/FATAL] [FML]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Quark Plugin (Quark-r1.6-178.jar)
  RandomPatches (randompatches-1.12.2-1.13.0.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  HCASM (HammerCore-1.12.2-2.0.6.13.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/2/20 8:34 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.entity.item.EntityItem.func_174872_o()I
	at mrtjp.projectred.expansion.TileTeleposer.makeEntityHeld(TileTeleposer.scala:303)
	at mrtjp.projectred.expansion.TileTeleposer$$anonfun$updateHeldItems$1.apply(TileTeleposer.scala:152)
	at mrtjp.projectred.expansion.TileTeleposer$$anonfun$updateHeldItems$1.apply(TileTeleposer.scala:151)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at mrtjp.projectred.expansion.TileTeleposer.updateHeldItems(TileTeleposer.scala:151)
	at mrtjp.projectred.expansion.TileTeleposer.updateServer(TileTeleposer.scala:104)
	at mrtjp.core.block.MTBlockTile.func_73660_a(tileblock.scala:455)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mrtjp.projectred.expansion.TileTeleposer.makeEntityHeld(TileTeleposer.scala:303)
	at mrtjp.projectred.expansion.TileTeleposer$$anonfun$updateHeldItems$1.apply(TileTeleposer.scala:152)
	at mrtjp.projectred.expansion.TileTeleposer$$anonfun$updateHeldItems$1.apply(TileTeleposer.scala:151)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at mrtjp.projectred.expansion.TileTeleposer.updateHeldItems(TileTeleposer.scala:151)
	at mrtjp.projectred.expansion.TileTeleposer.updateServer(TileTeleposer.scala:104)
	at mrtjp.core.block.MTBlockTile.func_73660_a(tileblock.scala:455)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)

-- Block entity being ticked --
Details:
	Name: projectred-expansion:machine2|7 // mrtjp.projectred.expansion.TileTeleposer
	Block type: ID #395 (tile.projectred.expansion.machine2 // mrtjp.projectred.expansion.BlockMachine // projectred-expansion:machine2)
	Block data value: 7 / 0x7 / 0b0111
	Block location: World: (-1232,64,2272), Chunk: (at 0,4,0 in -77,142; contains blocks -1232,0,2272 to -1217,255,2287), Region: (-3,4; contains chunks -96,128 to -65,159, blocks -1536,0,2048 to -1025,255,2559)
	Actual block type: ID #395 (tile.projectred.expansion.machine2 // mrtjp.projectred.expansion.BlockMachine // projectred-expansion:machine2)
	Actual block data value: 7 / 0x7 / 0b0111
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-1062.12.1.el7.x86_64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 151437712 bytes (144 MB) / 1132986368 bytes (1080 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 6 total; -Xms256M -Xmx4096M -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 106
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 87 mods loaded, 87 mods active
```

**Comment by 016Nojr** [comment] 2021-05-06 14:36
If this issue is still present in an update that will be released in a few days I can unfortunately not do anything with it as the mod version isnt supported anymore

**Closed as completed by 016Nojr** 2021-05-06 14:36 UTC
Labels: bug

**Comment by Darkona** [comment] 2021-09-17 04:38
Hello. Was this issue closed with a fix or not because of unsupported version? Also, a server crash (I just discovered it does crash in 1.12.2, in an unfortunate event) is a good reason to go back to a version for a fix.
