### ISSUE TITLE
NBT / Meta Conflict (ReBattery, Energy Crystal)

### ISSUE THREAD

**Issue by Wurmatron** [FTBTeam/FTB-Ultimate-Reloaded#41] opened 2019-02-15 17:58 UTC
* **Modpack Version**: 1.0.1

* **Issue**: NBT / Meta Conflict with multiple recipes using <ic2:re_battery> and <ic2:energy_crystal>
IE: Most Non IC2 recipes that use these items. (LV Capacitor,Mv Capacitor, AESU, Fusion Computer)

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**:  Yes, Its just a recipe/script issue

* **Mod/s Affected**: TechReborn, Modular PowerSuits (powersuits)

* **Known Fix**: #14, #15 (Same Bug /Underlying Issue)

**Comment by modmuss50** [comment] 2019-02-15 21:28
Duplicate of #14 and #15  and #44 

I have fixed this in the next TR update.

**Closed as completed** 2019-02-16 00:15 UTC
Labels: duplicate
